# Generated by Django 5.0.6 on 2024-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='Qr_codes/'),
        ),
    ]
