# Generated by Django 5.0.6 on 2024-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
