# Generated by Django 5.0.6 on 2024-07-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_qr_code'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('#0', 'RENTED'), ('#1', 'RETURNED'), ('#2', 'LOST'), ('#3', 'DELAYED')], max_length=2)),
                ('rent_start_date', models.DateField(help_text='when the book was rented')),
                ('rent_end_date', models.DateField(blank=True, help_text='deadline')),
                ('return_date', models.DateField(blank=True, help_text='actual return date')),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
