# Generated by Django 5.0.6 on 2024-07-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
    ]
